# Page settings
baseurl = "/"
title = "Elate theme"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["/css/custom1.css", "/css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "webuimaker@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""
  
  
	
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"

[[menu.main]]
    name = "Claratti Cloud"
    url = "/claratti-cloud/"
    weight = 2
    identifier = "claratti-cloud"

[[menu.main]]
    name = "lms"
    url = "/ims/"
    weight = 3
    identifier = "lms"

[[menu.main]]
    name = "Appointment"
    url = "/appointment/"
    weight = 4
    identifier = "appointment"

[[menu.main]]
    name = "Projectisago"
    url = "/piago/"
    weight = 4
    identifier = "piago"

[[menu.main]]
    name = "Contact"
    url = "/Contact/"
    weight = 5
    identifier = "contact"
  
  
  
  
  
  
  

  # Navigation
  [params.navigation]
    brand = ""
    logo = "/images/gwella-logo.png"
  
  # Hero section
  [params.hero]
    title = "Business Solutions"
    subtitle = 'Learning Management, Systems Integration, E-Learning and Cloud ICT Solutions'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "E-LEARNING PORTAL"
    description = "About to be deployed is a full e-commerce e-Learning portal to up skill and onboard your staff. Some examples courses in our library include active threat & situation awareness, first aid, social media responsibility in the workplace, anti-harassment and bullying, office ergonomics. Alternatively we can customise a separate LMS cloud platform for you.  "
    url = "#"
    button = ""
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "ONBOARD / INDUCTION STAFF PACKAGES"
    description = "Gwella can work with you and configure multiple courses to a specific on-boarding package just for you. Having a single package is easy to deploy, report on and manage - simply point your staff to log on and the courses you want them to complete are already assigned!"
    url = "#"
    button = ""
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "CUSTOM LMS CLOUD PLATFORMS"
    description = "After your own LMS branded portal hosted in the cloud? Gwella can create and customise your very own LMS e-Learning portal. Then you can either take over managing it yourself, or we can help with hosting, configuration and ongoing support on your behalf and let you get back to doing the things you do well. Inquire on the form below for further info."
    url = "#"
    button = ""
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"
      
      
  # Solution
  [params.solution]
    enable = true
    title = "Gwella Solutions"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.solution.row]]
      img = ""
      alt = "Image2"
      title = "BUSINESS PROCESS REVIEW"
      subtitle = "When is the last time you took a step back to check on the 'bigger picture' of how you're operating?  Have you entrusted key staff to these key areas and maybe feel some direction is lost or you would like a 'fresh set of eyes' on your key business processes.  Gwella have performed formal business process review for dozens of companies in vast areas of operations.  A small investment could identify or save an irrecoverable issue presenting itself. "

    [[params.solution.row]]
      img = ""
      alt = "Image2"
      title = "WORKFLOW ANALYSIS"
      subtitle = "Whether you have one employee or hundreds, workflows and processes are everywhere and can really hinder your business.  Let Gwella review these and suggest improvements and automations to free up time and improve accuracy in these workflows which are central in operations for your business."

    [[params.solution.row]]
      img = ""
      alt = "Image3"
      title = "ONGOING SUPPORT"
      subtitle = "Whilst post implementation support is down on the initial list of requirements when deciding on a project vendor it regularly shoots to the top of the list once the project has been 'implemented'.  Gwella understands this and can offer a number of post support packages to ensure you continue to get maximum effectiveness and possible improvements well in to the future."

    [[params.solution.row]]
      img = ""
      alt = "Image4"
      title = "SYSTEM INTEGRATIONS / INTERFACES"
      subtitle = "HR, CRM, document management, Sales funnel, Invoicing, payroll...the list goes on.  One system for this, that and the other.  Re-entry of the same data, human error, time away from growing your business.  You'd be surprised what can be automated now with such clever affordable tools.  Gwella are not only experts in understanding the business requirements of data but we are nerds at implementing tools and programs to optomise all these internal data flows."

    [[params.solution.row]]
      img = ""
      alt = "Image5"
      title = "PROJECT MANAGEMENT"
      subtitle = "It's all very well identifying the improvements your business needs and then giving the green light, you may not have the time, expertise or resources to get your project delivered on time, withing scope and within budget.  Let Gwella Project Manage this for you to a level that suits your budget, business and more importantly employees for maximum return."

  # company section
  [params.company]
    enable = true
    title = "Business Solutions"
    description = "Learning Management, Systems Integration, E-Learning and Cloud ICT Solutions"
    content = "<p>Based in Brisbane, Australia Gwella Pty Ltd typically engage with businesses small and large looking to improvement solutions and assistance.  We specialise in all business process improvement matters, from the seed of a new idea to the final product, or improvements to your existing systems. </p> <p>As well as providing expertise in Business Solutions by way of Project management, business analysis, system and software design Gwella is also proudly an affiliate partner of TalentLMS Learning Management SaaS, and Authorised Agent for Claratti ICT Solutions</p> <p>Our consultants and developers have been practicing for over a decade and have experience with organisations in Australia, New Zealand and Asia Pacific. From large mining companies, construction firms, retail outlets and owner operators we love to hear those words at the end of a project.  Either 'We're glad we engaged you to deliver this', or 'we love the system you have now implemented'.   </p>"
    button = "Learn More"
    buttonUrl = "/contact/"

  # ICTsolutions section
  [params.ICTsolutions]
    enable = true
    title = "Claratti ICT Solutions"
    description = ""

    [[params.ICTsolutions.item]]
      text = "VIRTUAL WORKSPACE"

    [[params.ICTsolutions.item]]
      text = "VOICE SERVICES"

    [[params.ICTsolutions.item]]
      text = "VIRTUAL SERVERS & STORAGE"

    [[params.ICTsolutions.item]]
      text = "LOCAL NETWORK SERVICES"

    [[params.ICTsolutions.item]]
      text = "ROUTING & QUALITY OF SERVICE"

    [[params.ICTsolutions.item]]
      text = "CONNECTIVITY 'CARRIAGE'"

    [[params.ICTsolutions.item]]
      text = "FIREWALL & SECURITY SERVICES"

    [[params.ICTsolutions.item]]
      text = "SECURE INTERNET ACCESS"
      
    [[params.ICTsolutions.item]]
      text = "DISASTER RECOVERY"
      
      
  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Gwella Pty Ltd is a boutique business consultancy that provides expert advice, services and internal business improvements to companies small and large."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "12 Beeby St, Wavell Heights, QLD 4012, <br>ACN: 616 412 090 | ABN: 75 616 412 090"],
        ["icon-phone", "(61) 7 3040 7681"],
        ["icon-envelope", "info@gwella.com.au"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Gwella.com.au  - Brisbane, Australia. All Rights Reserved.'
    links = [
        ["icon-linkedin", "https://www.linkedin.com/in/csnowling"],
        ["icon-facebook", "https://www.facebook.com/GwellaPtyLtd/"],
        ["icon-twitter", "#https://twitter.com/GwellaPtyLtd"]
      ]
